name: crm-kdu

services:
  postgres:
    image: postgres
    container_name: crm-kdu-postgres
    environment:
      POSTGRES_DB: crm-kdu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54329:5432"
    volumes:
      - crm-kdu_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  crm-kdu_postgres_data:
